steps:
  # see https://www.npmjs.com/package/editorconfig-checker
  - id: eclint
    name: "e53e225/editorconfig-checker"

  - id: go_version
    name: "gcr.io/cloud-builders/go"
    args: ["version"]
    env: ["GOPATH=.", "GO111MODULE=on"]

  - id: go_linter
    name: "golangci/golangci-lint"
    args: ["golangci-lint","run"]
    env: ["GOFLAGS=-mod=vendor"]

  - id: go_test
    name: "gcr.io/cloud-builders/go"
    args: ["test","helloworld"]
    env: ["GOPATH=."]

  - id: go_security
    name: "securego/gosec"
    args: ["helloworld"]
    env: ["GOPATH=.", "GO111MODULE=on"]
